### ISSUE TITLE
settings.json does not exist

### ISSUE THREAD

**Issue by guystreeter** [daw1012345/vscode-for-toolbox#5]
Running `./install.py` I get:
```
Telling VSCode to use podman instead of Docker
Traceback (most recent call last):
  File "/home/guy/external/vscode-for-toolbox/./install.py", line 36, in <module>
    write_vscode_config()
  File "/home/guy/external/vscode-for-toolbox/./install.py", line 9, in write_vscode_config
    with open(global_config_path, 'r+') as fd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/guy/.var/app/com.visualstudio.code/config/Code/User/settings.json'
```
The directory exists and has other contents:
```
$ ls -l /home/guy/.var/app/com.visualstudio.code/config/Code/User/
total 4
drwxr-xr-x. 1 guy guy 150 Feb 27 15:52 globalStorage
drwxr-xr-x. 1 guy guy   0 Feb 27 15:49 History
drwxr-xr-x. 1 guy guy   0 Feb 27 15:49 snippets
drwxr-xr-x. 1 guy guy  26 Feb 27 15:49 workspaceStorage
```
`find ~/.var/app/com.visualstudio.code -name settings.json` doesn't find the file in that directory structure anywhere.

**Comment by guystreeter** [comment]
I started vscode and changed some setting, and now the file exists.

**Comment by daw1012345** [comment]
Thanks for the report @guystreeter. I changed the installation script to create `settings.json` if it does not exist.
